### ISSUE TITLE
NGL Viewer Displays Hydrogen Instead of Chlorine Atoms

### ISSUE THREAD

**Issue by wverastegui** [usegalaxy-eu/galaxy#229] opened 2024-03-19 12:01 UTC
**Describe the bug**
The NGL viewer plugin in Galaxy is visualizing hydrogen atoms instead of chlorine atoms.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.5.dev0

**To Reproduce**
1. Load the molecule in pdb format from the attached zip file ([mirex.zip](https://github.com/usegalaxy-eu/galaxy/files/14647224/mirex.zip)).
2. Go to the "Visualize" section and select the NGL viewer plugin.

**Expected behavior**
The tool should display the chlorine atoms instead of hydrogen atoms (white) as shown in the screenshots.

**Screenshots**

1. [Correct visualization with NGL viewer]<img width="950" alt="ngl_viewer" src="https://github.com/usegalaxy-eu/galaxy/assets/88352798/c2ba6b74-eb5f-4e97-b3b0-ad95236127a9">

3. [Incorrect visualization with NGL tool]<img width="600" alt="ngl_galaxyeu" src="https://github.com/usegalaxy-eu/galaxy/assets/88352798/20d11e65-ea1a-422c-9d32-788743883b1f">

**Additional context**
- The molecule visualization works correctly with the NGL viewer at [nglviewer.org](http://nglviewer.org/ngl/).

**Comment by bgruening** [comment] 2024-03-19 15:48
@wverastegui can it be that the old version we are shipping is doing it wrong? Maybe an update to the new version can fix that?

**Comment by hechth** [comment] 2024-04-18 14:21
It seems like the new version seems to handle this correctly, assumed that the web version has the latest version.

**Comment by bgruening** [comment] 2024-04-18 20:53
@itisAliRH can you please look at this and update the plugin in Galaxy?

**Comment by itisAliRH** [comment] 2024-04-19 11:15
@bgruening Sure, I'll take a look!

**Comment by itisAliRH** [comment] 2024-04-19 16:34
There is an error in rendering options for this visualisation and default values are not loaded. I opened galaxyproject#18030 which is related.

**Comment by bgruening** [comment] 2024-04-19 16:45
@itisAliRH something you can fix?

**Comment by itisAliRH** [comment] 2024-04-19 16:51
> @itisAliRH something you can fix?

Working on it...

**Comment by hechth** [comment] 2024-04-30 12:05
@itisAliRH let me know if there is anything we can help with and ping me or @wverastegui !

**Comment by itisAliRH** [comment] 2024-06-03 14:01
It's fixed on galaxyproject#18299. Feel free to reopen this issue if the problem is still there @hechth @wverastegui

**Closed as completed by itisAliRH** 2024-06-03 14:01 UTC

**Comment by hechth** [comment] 2024-06-04 11:43
Thanks Alireza :) @wverastegui can you check if this is correct on usegalaxy.org or eu? Not sure if EU is running version 24.1 already though.

**Comment by wverastegui** [comment] 2024-06-04 12:17
Thanks Alireza !. @hechth, neither of them is running version 24.1. The problem still persists in version 24.0.3.

**Comment by itisAliRH** [comment] 2024-06-04 14:41
@hechth You're welcome✌🏻 The 24.1 has not been released yet and will be available soon on EU.
